### ISSUE TITLE
gmusic_receiver problem

### ISSUE THREAD

**Issue by ajfriesen** [tprelog/GoogleMusic_HomeAssistant#1]
I tried to install this custom component on 94.1

And I get this warning in the logs:

Log Details (WARNING)
Mon Jun 10 2019 22:57:24 GMT+0200 (Central European Summer Time)
Could not render template gmusic_receiver, the state is unknown.

Does this component load playlists and stations?
I am not sure if I have to choose from the list because I can not submit a value from the user interface.

**Comment by tprelog** [comment]
Sorry for the delayed response.

Yes this component should load both playlist and stations. (Only stations that you have added to your library, I could make it to add every station but for me that list was over 150 stations)

when the component loads it should populate two separate drop-down lists. one containing playlist (like og switch) and a separate containing stations (Even if you have not added stations to your library you should still see the "l'm feeling lucky")

At this time You should be able to make a selection from the drop down list similar to the original switch or use the media_player. play_media service. The input select do not necessarily need to be shown in the front end but they do need to exist even if they remain hidden. At this time even the play_media service still requires the input selects however this requirement will hopefully change in the future.

Ideally I would like to make all the input select completely optional. I have a busy few weeks traveling for work right now but should have time to get back to this when Im home again.

The gmusic_receiver is a template sensor. I assume you're seeing the error message in the HA GUI?

If I'm not mistaken you are using hass.io correct? Can you please try displaying the logs from the command line while hass is starting? There may be more information related to your error.

**Comment by ajfriesen** [comment]
Sorry for the lack of information.

Yes I am running Hass.io on my ubuntu server.

The only interesting message regarding this component when starting home assistant is this:

```
2019-06-12 21:37:20 INFO (MainThread) [homeassistant.components.automation] Initialized trigger gmusic_player_auto_play
...
2019-06-12 21:37:20 WARNING (MainThread) [homeassistant.components.template.sensor] Could not render template gmusic_receiver, the state is unknown.
...
```

If you want you even can see my config since I have it on github: https://github.com/ajfriesen/home_assistant_configuration

The stuff I added for your custom component is in this commit:
https://github.com/ajfriesen/home_assistant_configuration/commit/15ea5177115dad0d71efe68b95fec4a8425d304a

I did reread everything again and think I added everything which you mentioned on the README.

When checking my config with travis or the add on for checking your config I get this message:

https://travis-ci.org/ajfriesen/home_assistant_configuration/builds/544899869
```
[23:15:03] INFO: Installing Home Assistant: latest...
[23:15:03] INFO: Please be patient, this might take a few minutes...
[23:15:49] INFO: Installed Home Assistant 0.94.2
[23:15:49] INFO: Don't worry, this temporary installation is not overwriting your current one.
[23:15:49] INFO: Making a copy of your configuration for checking...
[23:15:58] INFO: Checking your configuration against this version...
[23:16:43] ERROR: The configuration check did not pass!
[23:16:43] ERROR: See the output below for more details.
INFO:homeassistant.util.package:Attempting install of colorlog==4.0.2
Testing configuration at /tmp/config
INFO:homeassistant.util.package:Attempting install of influxdb==5.2.0
INFO:homeassistant.util.package:Attempting install of aiohttp_cors==0.7.0
INFO:homeassistant.util.package:Attempting install of sqlalchemy==1.3.3
INFO:homeassistant.util.package:Attempting install of distro==1.4.0
INFO:homeassistant.util.package:Attempting install of home-assistant-frontend==20190604.0
INFO:homeassistant.util.package:Attempting install of mutagen==1.42.0
INFO:homeassistant.util.package:Attempting install of netdisco==2.6.0
Failed config
  General Errors: 
    - Integration gmusic_player not found when trying to verify its media_player platform.

Successful config (partial)
```

And as stated above, I do not get any values in the input selects. The fieds are just greyed out.
![image](https://user-images.githubusercontent.com/6827967/59381746-7b7fee00-8d5c-11e9-95d1-bf776fa7df8a.png)


Did I miss something?

**Comment by ajfriesen** [comment]
I also remembered that you had to install gmusicapi for the old gmusic switch so I added this to my gmusic-player.yaml

```
# Hassio specfic

## Command line to install gmusicapi
shell_command:
  install_gmusic: pip3 install gmusicapi==11.0.4

## Automations to install gmusic on homeassistant start
automation:
  - alias: homeassistant_start_gmusic
    hide_entity: true
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: shell_command.install_gmusic
```

I double checked and logged into the homeassistant container from my hassio installation and could see the the gmusicapi pip package.

But still the same behavior.

**Comment by tprelog** [comment]
I have through your config and I cannot see anything obvious that is incorrect or missing. Since the error seems to be related to the sensor maybe we can try to comment that out and see if the component will load.

Just for the sake of troubleshooting can you please comment out lines 69 -105 and also lines 116 -118 and try the component again. With all those lines commented out it will not autoplay or auto-track advance but for now I'm just trying to figure out why it is not loading properly. 

Thanks for your patience. 🙂

**Comment by ajfriesen** [comment]
Did you mean to comment the lines out from the gmusic-player.yaml or the custom-component itself?

For the yaml that would be just broken, I guess you mixed the lines here, but just a guess.

Anyhow, will have more time tomorrow for investigating.

Thanks so far!

**Comment by tprelog** [comment]
Sorry... All lines should be commented out on the gmusic_player.yaml. You are correct, this will break some functionality of the component but it should not prevent it from loading.

**Comment by ajfriesen** [comment]
Okay, commenting out everything from the gmusic_player.yaml will let home assistant config check pass.

**Comment by ajfriesen** [comment]
So as soon as I have this in my config:

```
media_player:
  - platform: gmusic_player
```

I will get this:

```
Failed config
  General Errors: 
    - Integration gmusic_player not found when trying to verify its media_player platform.
```

**Comment by tprelog** [comment]
I was having problems like this while I was following the development 101 guide on Hass. if I made mistake on my configuration has would fail to pass the conflict check and would not reboot. Even after I corrected my files hass still refused to correctly pass config. I had to remove the component and reboot Hass I could then add the component back and it would now pass config without making any additional changes. 

I need a post in the forum but I got no response from anyone.
https://community.home-assistant.io/t/having-trouble-with-examples-in-home-assistant-core-101/115735

Can you please try these steps.

1. remove only the gmusic_player.yaml (You can leave all the files in the custom components in place) then reboot Hass. 

2. Add the g music player.yaml back to Hass

3. Skip the config check and just reboot instead.

This is just a very weird issue I've encountered but it only happens in Hass.io I do not have this problem on my main home assistant installation that simply runs in a virtual environment.

**Comment by tprelog** [comment]
I am wondering if this is because I am using a package file for the configuration. But still the problem only exists it Hass.io when running home assistance from a virtual environment

**Comment by ajfriesen** [comment]
I think I did what you requested:

1. Moved my gmusic_player.yaml to a snippets folder which is not used by home assistant
2. reboot
3. move that file back into my components/includes folder
4. reboot

But still get the error: 
```Could not render template gmusic_receiver, the state is unknown.```

**Comment by tprelog** [comment]
The only other thing I have just noticed, Im not sure if it matters but I have gmusic_player.yaml directly inside my packages directory at the top level. I just noticed that you have several folder levels inside of your packages directory.

I would assume this generally is working correctly for you or you would not have your setup done this way. If you have time for giggles can you try moving gmusic_player.yaml to the top level inside of your packages directory.

I know that @underknowledge on the HA forums is also using hass.io and he does have this working

**Comment by tprelog** [comment]
I'm using a template sensor named gmusic_receiver as a worker around to advance to the next track when a song ends.

Something else to possibly try is combining our troubleshooting steps above.

what I mean is to leave the lines of code commented out as suggested above and then try the last three steps (remove, reboot , add agaon and reboot) again. But leave the lines in gmusic_player.yaml commented out when you add the file back

**Comment by ajfriesen** [comment]
Tried that as well and still same. Can not load a playlist or station.

Regarding the package location: That should not make any problems. Using that a long time now and did steal this from frenck and adjusted it a little.

Would be great to see a working config on github or something from another hassio user.

**Comment by tprelog** [comment]
Maybe @underknowledge can share his config. He's the only other person I know of that is using this component for sure and he is also using hass.io

Im not sure if he is using github though.

**Comment by tprelog** [comment]
I'm out of town for work right now but I will be home this weekend. I will also try to make a different package file for you and remove absolutely everything that is not needed.

I'm sorry I cannot offer any other suggestions at this moment. But I will get back to you if I think of something or when I get home and create that new package file for you.

**Comment by ajfriesen** [comment]
No worries, you already helped a lot.
I think I will repost this in the forum, there might be more people than on github.

Just wanted that to track for you on github, since that is easier for development.

**Comment by tprelog** [comment]
Thanks! Ill be sure to follow along in the forum as well.

**Comment by Underknowledge** [comment]
even getting notifications

```yaml
## Google Music in Home Assistant as a media_player
## Stream playlists and stations from your Google Music library

## Use this 'package.yaml' file to configure "gmusic_player"

media_player:
  - platform: gmusic_player

    ## Enter a valid device_id here or in your secrets.yaml
    device_id: !secret gmusic_device_id

    ## Set login_type to access Google Music
    ## valid options are 'legacy' or 'oauth'
    login_type: oauth

    ## OAUTH login -- not required if using 'legacy' login
    ## https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.perform_oauth
    ## Set path to existing oauth credentials file.
    oauth_cred: '/config/appdaemon/GoogleMusic.oauth'

    ## LEGACY login -- not required if using 'oauth' login
    ## https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.login
    ## Authenticate using full account credentials.
    ## Set username and password here or in your secrets.yaml
    user: !secret gmusic_user
    password: !secret gmusic_password
    ## Optional for legacy-login - Directory with RW access for "gmusic_authtoken"
    token_path: '/config/appdaemon/.'

    ## Set various input_select REQUIRED by gmusic_player,
    ## future plan is to make these optional but for now
    ## PLEASE DO NOT REMOVE OR CHANGE THESE (Not Yet!)
    media_player: 'gmusic_player_speakers'
    source: 'gmusic_player_source'
    playlist: 'gmusic_player_playlist'
    station: 'gmusic_player_station'

## Various input_select REQUIRED by gmusic_player
## PLEASE DO NOT REMOVE OR CHANGE THESE (Not Yet!)
## ONLY EDIT TO ADD YOUR MEDIA_PLAYERS BELOW
input_select:
  gmusic_player_speakers:
    name: Speakers
    icon: mdi:speaker
    options: ## ONLY HERE - Replace with entity_ids of your own media_players
    - bad
    - mini
    - kuche
    - alle
  gmusic_player_source:
    name: Source
    icon: mdi:library-music
    options:
    - "Playlist"
    - "Station"

  gmusic_player_playlist:
    name: Playlist
    icon: mdi:playlist-music
    options: ## Should be empty
    - " "

  gmusic_player_station:
    name: Station
    icon: mdi:playlist-music
    options:  ## Should be empty
    - " "

## Used for auto track advance.
sensor:
  - platform: template
    sensors:
      gmusic_receiver:
        value_template: "{{ states.media_player.gmusic_player.attributes._player_state }}"

automation old:
  - alias: "gmusic_player_auto_advance"
    hide_entity: true
    initial_state: 'on'
    trigger:
      platform: state
      #value_template: "{{ states.media_player.gmusic_player.attributes._player_state }}"
      entity_id: 'sensor.gmusic_receiver'
      from: 'playing'
      to: 'idle'
      for:
        seconds: 1
    condition:
      - condition: state
        entity_id: 'media_player.gmusic_player'
        state: 'playing'
    action:
      - service: media_player.media_next_track
        entity_id: 'media_player.gmusic_player'

  - alias: "gmusic_Player_auto_play"
    hide_entity: true
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: 'media_player.gmusic_player'
      from: 'off'
      to: 'idle'
    action:
      - service: media_player.media_play
        entity_id: 'media_player.gmusic_player'


## ------------------------------------------------------------------------- ,
##  --------------   The rest of this file is optional    ----------------
## ------------------------------------------------------------------------- ,
homeassistant:
  customize:
    media_player.gmusic_player:
      friendly_name: "Google Music Player"

    sensor.gmusic_receiver:
      friendly_name: "Google Music Receiver"
      hidden: true

## This group may only be visable when using the "states UI"
group:
  google_music_media_player:
    control: hidden
    name: Google Music
    entities:
    - media_player.gmusic_player
    - input_select.gmusic_player_speakers
    - input_select.gmusic_player_source
    - input_select.gmusic_player_playlist
    - input_select.gmusic_player_station


```

**Comment by ajfriesen** [comment]
I had a spelling mistake!

It was **custom_compontents** instead of **custom_components**

So now the config will pass the check.
No I have some login issue with oauth but legacy does work!

But that should can be solved on my end.

Felling dumb now :-D

**Comment by tprelog** [comment]
That's great news! Don't worry I make plenty of spelling mistakes myself.

So to confirm are you actually able to use the component now without needing to comment out the lines we had during troubleshooting?

Regarding the oauth login, the credentials file needs to be generated ahead of time. This is different from legacy login which will create a temporary credential file for you.

I'm not sure how you would go about generating the oauth credential file using Hassio. I had to generate the file on a different computer then transfer it to Hassio. Unfortunately I did not have time to add those instructions to my post before traveling for work. 

The steps I took to generate the file are however provided in my thread for using gmusic with appdaemon. If you want to take a look you can find them under the section for installing gmusicapi in a virtual environment.
https://community.home-assistant.io/t/google-music-in-ha-using-appdaemon/109983

**Comment by ajfriesen** [comment]
Yes everything is working now with this config when using legacy:

https://github.com/ajfriesen/home_assistant_configuration/blob/master/packages/components/includes/gmusic_player.yaml

I did generate the oauth file in the docker container from home assistant itself. 
Just did docker exec into the Container, but this is not possible for all hassio users.

There also were some errors about oauth but do not have time now to dig into that. Maybe I need to create that file properly again.

Will be back on Sunday, maybe I have time to figure out a good way for everybody to create that file and put it into the readme in the evening.

**Comment by ajfriesen** [comment]
From my side this can be closed.
